# INU_tools.core.plants_dat — GTA SA data/plants.dat reader / writer.
#
# plants.dat drives the engine's procedural grass (CPlantMgr). It is a
# plain TAB-separated text file with ';' comment lines. Each data line
# binds a COLPOINT surface *name* (e.g. GRASS_SHORT_LUSH) to one plant
# cover definition. A surface may have up to 3 definitions (PCDid 0-2).
#
# Column layout (from the vanilla file header, R* Andrzej Madajczyk):
#   Name PCDid SlotID ModelID UVoff R G B I VarI A
#   SclXY SclZ SclVarXY SclVarZ WBendScl WBendVar Density
#
# Grass has NO .dff model — the engine renders billboards from the
# "big" texture selected by SlotID (in plant1.txd), UVoff picking one of
# 16 vertical tiles. So editing plants.dat + plant1.txd is the whole job.
#
# This module is pure (no bpy) so it is unit-testable and reusable.

from __future__ import annotations


# Field spec: (key, kind). Order == column order in the file.
# kind 'i' = integer column, 'f' = float column, 's' = string (name).
PLANTS_FIELDS = (
    ("name",        's'),
    ("pcd_id",      'i'),
    ("slot_id",     'i'),
    ("model_id",    'i'),
    ("uv_off",      'i'),
    ("r",           'i'),
    ("g",           'i'),
    ("b",           'i'),
    ("intensity",   'i'),
    ("var_i",       'i'),
    ("alpha",       'i'),
    ("scl_xy",      'f'),
    ("scl_z",       'f'),
    ("scl_var_xy",  'f'),
    ("scl_var_z",   'f'),
    ("wbend_scl",   'f'),
    ("wbend_var",   'f'),
    ("density",     'f'),
)

_NUM_COLUMNS = len(PLANTS_FIELDS)

# Sensible defaults for a fresh entry (a small lush green tuft).
DEFAULT_ENTRY = {
    "name": "GRASS_SHORT_LUSH",
    "pcd_id": 0, "slot_id": 0, "model_id": 0, "uv_off": 1,
    "r": 220, "g": 210, "b": 165, "intensity": 160, "var_i": 22, "alpha": 40,
    "scl_xy": 0.5, "scl_z": 0.51, "scl_var_xy": 1.5, "scl_var_z": 0.65,
    "wbend_scl": 5.0, "wbend_var": 1.0, "density": 0.1,
}


def _fmt_float(v) -> str:
    """Format a float the way the vanilla file does: trailing zeros
    stripped but always at least one decimal (1.0, 0.11, 0.02)."""
    s = f"{float(v):.4f}".rstrip('0').rstrip('.')
    if '.' not in s:
        s += '.0'
    return s


def parse_plants_dat(text: str):
    """Parse plants.dat text into a list of entry dicts.

    Comment (';') and blank lines are skipped. Malformed lines (wrong
    column count / non-numeric) are skipped too — returned alongside the
    entries so the caller can report them.

    Returns: (entries, skipped) where entries is a list of dicts keyed by
    PLANTS_FIELDS names and skipped is a list of (line_no, raw) tuples.
    """
    entries = []
    skipped = []
    for line_no, raw in enumerate(text.splitlines(), start=1):
        line = raw.strip()
        if not line or line.startswith(';') or line.startswith('#'):
            continue
        parts = line.split()
        if len(parts) != _NUM_COLUMNS:
            skipped.append((line_no, raw))
            continue
        entry = {}
        ok = True
        for (key, kind), tok in zip(PLANTS_FIELDS, parts):
            try:
                if kind == 's':
                    entry[key] = tok
                elif kind == 'i':
                    entry[key] = int(tok)
                else:
                    entry[key] = float(tok)
            except ValueError:
                ok = False
                break
        if ok:
            entries.append(entry)
        else:
            skipped.append((line_no, raw))
    return entries, skipped


_HEADER_LINES = [
    ";",
    ";\tplants.dat - regenerated by INU Tools",
    ";\tProcedural grass definitions (CPlantMgr). TAB-separated.",
    ";",
    ";Name\tPCDid\tSlotID\tModelID\tUVoff\tR\tG\tB\tI\tVarI\tA"
    "\tSclXY\tSclZ\tSclVarXY\tSclVarZ\tWBendScl\tWBendVar\tDensity",
    ";",
]


def _format_line(entry: dict) -> str:
    cells = []
    for key, kind in PLANTS_FIELDS:
        v = entry.get(key, DEFAULT_ENTRY.get(key, 0))
        if kind == 'f':
            cells.append(_fmt_float(v))
        else:
            cells.append(str(v))
    return "\t".join(cells)


def _is_data_line(line: str) -> bool:
    s = line.strip()
    return bool(s) and not s.startswith(';') and not s.startswith('#')


def format_plants_dat(entries) -> str:
    """Serialise entries to plants.dat text from scratch (used only when no
    template file exists). Grouped by surface, CRLF, no blank data lines."""
    out = list(_HEADER_LINES)
    last_name = None
    for e in entries:
        name = e.get("name", "")
        if last_name is not None and name != last_name:
            out.append(";")
        out.append(_format_line(e))
        last_name = name
    out.append(";")
    out.append(";the end")
    return "\r\n".join(out) + "\r\n"


def rewrite_plants_dat(template_text: str, entries) -> str:
    """Rewrite plants.dat PRESERVING the template's comments, header and
    layout — only the data lines are replaced by `entries` (in order).

    This keeps the file byte-compatible with what the game accepts: the
    original documentation block, group separators and footer are kept
    verbatim; no stray blank lines are introduced. Removed entries drop
    their line; added entries are appended after the last data line.
    """
    entries = list(entries)
    eol = "\r\n" if "\r\n" in template_text else "\n"
    lines = template_text.split(eol)

    data_positions = [i for i, l in enumerate(lines) if _is_data_line(l)]
    last_data = data_positions[-1] if data_positions else -1

    out = []
    ei = 0
    extras_done = False
    for i, l in enumerate(lines):
        if _is_data_line(l):
            if ei < len(entries):
                out.append(_format_line(entries[ei]))
                ei += 1
            # else: entry removed → drop this template data line
        else:
            # Flush any extra (newly-added) entries just after the block of
            # data lines, before the footer/trailing comments.
            if i > last_data and not extras_done and ei < len(entries):
                out.extend(_format_line(e) for e in entries[ei:])
                ei = len(entries)
                extras_done = True
            out.append(l)
    if ei < len(entries):
        out.extend(_format_line(e) for e in entries[ei:])
    return eol.join(out)
